all:
	g++-8 -o atomic AtomicWrite.cpp -Wpsabi -msse3 -msse2 -msse2avx  -mavx5124fmaps -mavx5124vnniw -mavx512bitalg -mavx512bw -mavx512cd -mavx512dq -mavx512er -mavx512f -mavx512ifma -mavx512pf -mavx512vbmi -mavx512vbmi2 -mavx512vl -mavx512vnni -mavx512vpopcntdq

